service: memories-app
frameworkVersion: '2'

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  environment:
    MEMORIES_TABLE_NAME: memories-table-memories-app-${self:provider.stage}
    MEMORIES_BY_USER_INDEX_NAME: memories-by-user-index-memories-app-${self:provider.stage}
    PHOTOS_S3_BUCKET_NAME: memories-photos-bucket-memories-app-${self:provider.stage}
    POST_SIGNED_URL_EXPIRATION: 300
    GET_SIGNED_URL_EXPIRATION: 86400
  httpApi:
    cors: true
    authorizers:
      jwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - '${opt:region, self:provider.region}'
              - '.amazonaws.com/'
              - Ref: CognitoUserPool
        audience:
          - Ref: CognitoUserPoolClient
functions:
  generateUploadUrl:
    handler: src/lambda/generateUploadUrl.handler
    events:
      - httpApi:
          path: /memories/{memoryId}/generate-upload-url
          method: post
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.PHOTOS_S3_BUCKET_NAME}/*
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
  createMemory:
    handler: src/lambda/createMemory.handler
    events:
      - httpApi:
          path: /memories
          method: post
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
  getMemories:
    handler: src/lambda/getMemories.handler
    events:
      - httpApi:
          path: /memories
          method: get
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}/index/${self:provider.environment.MEMORIES_BY_USER_INDEX_NAME}
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.PHOTOS_S3_BUCKET_NAME}/*
  getMemory:
    handler: src/lambda/getMemory.handler
    events:
      - httpApi:
          path: /memories/{memoryId}
          method: get
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.PHOTOS_S3_BUCKET_NAME}/*
  updateMemory:
    handler: src/lambda/updateMemory.handler
    events:
      - httpApi:
          path: /memories/{memoryId}
          method: put
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
  deleteMemory:
    handler: src/lambda/deleteMemory.handler
    events:
      - httpApi:
          path: /memories/{memoryId}
          method: delete
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
  deleteMemoryImage:
    handler: src/lambda/deleteMemoryImage.handler
    events:
      - httpApi:
          path: /memories/{memoryId}/images/{imageId}
          method: delete
          authorizer: jwtAuthorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MEMORIES_TABLE_NAME}
resources:
  Resources:
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: memories-app-user-pool-${self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireNumbers: True
            RequireSymbols: True
    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: memories-app-user-pool-client-${self:provider.stage}
        SupportedIdentityProviders: ["COGNITO"]
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthFlows: ["implicit"]
        CallbackURLs: ["http://localhost:3000/callback"]
        LogoutURLs: ["http://localhost:3000/logout"]
        DefaultRedirectURI: "http://localhost:3000/callback"
        AllowedOAuthScopes: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"]
        GenerateSecret: false
        AccessTokenValidity: 24
        UserPoolId:
          Ref: CognitoUserPool
    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: memories-app-${self:provider.stage}
        UserPoolId:
          Ref: CognitoUserPool
    PhotosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PHOTOS_S3_BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
    MemoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MEMORIES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: memoryId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: memoryId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.MEMORIES_BY_USER_INDEX_NAME}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
